import type { AthenaSession, Topic, TranscriptTurn } from './types';

function formatDuration(ms: number): string {
  const total = Math.max(0, Math.round(ms / 1000));
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}m ${String(s).padStart(2, '0')}s`;
}

/**
 * Renders the revision summary a student takes away from the viva.
 *
 * Deliberately derived from recorded state rather than a closing LLM call: the
 * judgements in it are the same judgements the student watched land on the
 * chips during the session, so the document can never contradict what they saw.
 * It is also one less thing that can fail at the end of a demo.
 */
export function renderSummary(
  session: AthenaSession,
  topics: Topic[],
  transcript: TranscriptTurn[],
  durationMs: number,
): string {
  const strong = topics.filter((t) => t.status === 'correct' && !t.redeemed);
  const recovered = topics.filter((t) => t.redeemed);
  const shaky = topics.filter((t) => t.status === 'partial');
  const weak = topics.filter((t) => t.status === 'wrong');
  const untouched = topics.filter(
    (t) => t.status === 'unattempted' || t.status === 'active',
  );

  const date = new Date(session.createdAt).toLocaleString();
  const lines: string[] = [];

  lines.push('# Viva summary');
  lines.push('');
  if (session.sourceTitle) lines.push(`**Material:** ${session.sourceTitle}  `);
  if (session.sourceUrl) lines.push(`**Source:** ${session.sourceUrl}  `);
  lines.push(`**Date:** ${date}  `);
  lines.push(`**Length:** ${formatDuration(durationMs)}  `);
  lines.push(`**Topics examined:** ${topics.length}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  lines.push('## Where you were strong');
  lines.push('');
  if (strong.length === 0) {
    lines.push('_Nothing landed first time in this session._');
  } else {
    for (const t of strong) lines.push(`- **${t.name}** — answered correctly first time.`);
  }
  lines.push('');

  if (recovered.length > 0) {
    lines.push('## Where you recovered');
    lines.push('');
    lines.push(
      'You struggled with these at first and got them on a second pass. Worth one more look before the real thing — recovered is not yet solid.',
    );
    lines.push('');
    for (const t of recovered) {
      lines.push(`- **${t.name}** — correct on attempt ${t.attempts}.`);
    }
    lines.push('');
  }

  lines.push('## Where you need work');
  lines.push('');
  if (weak.length === 0 && shaky.length === 0) {
    lines.push('_No topic was left unresolved._');
  } else {
    for (const t of weak) {
      lines.push(`- **${t.name}** — could not be answered. Start here.`);
    }
    for (const t of shaky) {
      lines.push(`- **${t.name}** — partly understood; the detail was missing.`);
    }
  }
  lines.push('');

  if (untouched.length > 0) {
    lines.push('## Not covered');
    lines.push('');
    lines.push('The session ended before Athena reached these:');
    lines.push('');
    for (const t of untouched) lines.push(`- ${t.name}`);
    lines.push('');
  }

  lines.push('## Suggested revision order');
  lines.push('');
  const order = [...weak, ...shaky, ...recovered, ...untouched];
  if (order.length === 0) {
    lines.push('Re-run the viva on a harder passage — this one is done.');
  } else {
    order.forEach((t, i) => lines.push(`${i + 1}. ${t.name}`));
  }
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('## Transcript');
  lines.push('');
  if (transcript.length === 0) {
    lines.push('_No turns were recorded._');
  } else {
    for (const turn of transcript) {
      const who = turn.role === 'athena' ? 'Athena' : 'You';
      lines.push(`**${who}:** ${turn.text}`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(
    '_Generated by Athena. This is a study aid, not a graded assessment — Athena judges spoken answers in real time and can be wrong, particularly where speech recognition mishears a technical term. Treat it as a revision prompt, not a mark._',
  );
  lines.push('');

  return lines.join('\n');
}

/** Filesystem-safe name derived from the material being examined. */
export function summaryFilename(session: AthenaSession): string {
  const base = (session.sourceTitle ?? 'viva')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  const day = new Date(session.createdAt).toISOString().slice(0, 10);
  return `athena-${base || 'viva'}-${day}.md`;
}
