import WebSocket from 'ws';
const SID = process.argv[2];
const list = await (await fetch('http://127.0.0.1:9222/json/list')).json();
const ws = new WebSocket(list.find((t) => t.type === 'page').webSocketDebuggerUrl, { maxPayload: 64e6 });
let id = 0; const pending = new Map(); const errs = [];
const send = (m, p = {}) => new Promise((r) => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method: m, params: p })); });
await new Promise((r) => ws.on('open', r));
ws.on('message', (raw) => { const m = JSON.parse(raw.toString());
  if (m.id && pending.has(m.id)) { pending.get(m.id)(m.result); pending.delete(m.id); return; }
  if (m.method === 'Runtime.exceptionThrown') errs.push(m.params.exceptionDetails.exception?.description ?? m.params.exceptionDetails.text); });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const ev = async (e) => (await send('Runtime.evaluate', { expression: e, returnByValue: true })).result?.value;
await send('Runtime.enable'); await send('Page.enable');
await send('Page.navigate', { url: `http://localhost:3000/viva?s=${SID}&a=1` });
await wait(30000);
const type = async (t) => ev(`(() => { const i=document.getElementById('athena-typed'); if(!i) return 'NO INPUT';
  Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value').set.call(i, ${JSON.stringify(t)});
  i.dispatchEvent(new Event('input',{bubbles:true}));
  const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='Send');
  if(!b||b.disabled) return 'SEND DISABLED'; b.click(); return 'sent'; })()`);
const chips = async () => ev(`JSON.stringify([...document.querySelectorAll('.athena-chip')].map(c=>c.dataset.status+':'+c.textContent.trim().split(String.fromCharCode(8212))[0].trim()))`);
const banner = async () => ev(`(() => { const t=document.body.innerText; return t.includes('transcript is not') ? 'RTM WARNING SHOWN' : 'no rtm warning'; })()`);
const spoke = async () => ev(`document.body.innerText.includes('ATHENA') && document.querySelectorAll('li').length > 0 ? 'transcript present' : 'NO TRANSCRIPT'`);

console.log('[after orientation]', await spoke(), '|', await banner());
console.log('[start exam]', await type("I'm ready, examine me."));
await wait(20000);
console.log('[chips]', await chips());
console.log('[answer]', await type('All records sit in the linked leaf nodes, so a range scan just walks the leaf level.'));
await wait(20000);
console.log('[chips]', await chips());
console.log('[banner]', await banner());
console.log('[exceptions]', errs.length ? errs : 'none');
process.exit(0);
